apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    udm:
      sbi:   
      - addr:
         - 0.0.0.0
        port: 8099
        advertise: open5gs-udm
    nrf:
     sbi:
      name: open5gs-nrf
      port: 80
