apiVersion: v1
kind: ConfigMap
metadata:
  name: open5gs-udr-config
  labels:
    epc-mode: udr
data:
  udr.yaml: |
    logger:
        file: /var/log/open5gs/udr.log

    db_uri: mongodb://${MONGODB_ADMIN_USER}:${MONGODB_ADMIN_PASSWORD}@mongodb-svc/admin
    udr:
      sbi:
      - addr:
         - 0.0.0.0
        port: 8099
        advertise: open5gs-udr
    nrf:
     sbi:
      name: open5gs-nrf  
      port: 80
